### PR TITLE
Accept Dynamic Entries and RuntimeChunks

### PR DESCRIPTION
**Pull request by azizhk**
Hi,
I'm trying to integrate this plugin with next.js (https://github.com/zeit/next.js/issues/7563)
Next.js has Dynamic Entries, [Webpack Documentation](https://webpack.js.org/configuration/entry-context/#dynamic-entry)
Source:
https://github.com/zeit/next.js/blob/a71cb644b5b7f45521d7a49f5cfca171b3d81a1e/packages/next/build/webpack-config.ts#L336-L341

So had to make a few changes.

### CODE REVIEW

**Comment by prateekbh** [comment]
Thanks for this work :)

Can you post a small sample `webpack` config for this? I'll use for adding tests?

**Comment by azizhk** [comment]
I'll add tests itself.

**Comment by azizhk** [comment]
I've added the tests. I might have gone overboard with the various configs, so let me know and I'll delete whatever is unnecessary. A few files are the same. I don't know if I should de-duplicate or let them be? These files would have to be split if webpack modifies it's runtime to use es2015+ features (highly unlikely).

**Comment by prateekbh** [comment]
This looks great thanks 👍

**Pull request merged**
