### PR TITLE
Fix resolved paths (and windows \ paths)

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by prateekbh** [comment]
Can you provide a sample config which these changes are targeting?

**Comment by prateekbh** [comment]
@forsakenharmony there is no build step to this project yet, do you think your changes will be supported for the preact-cli supported node versions?

**Comment by ForsakenHarmony** [comment]
Destructuring is node 6+, includes is node 4+

preact-cli is node 8+ because of async await

**Comment by prateekbh** [comment]
Will publish ASAP

**Comment by ForsakenHarmony** [comment]
For the sample config, it's basically just `require.resolve` instead of just the string in .babelrc or whatever else

**Comment by prateekbh** [comment]
added a test for this change

**Pull request merged**
