### PR TITLE
Keeps the hash same for parent and child compilation

### LINKED ISSUE #15: Different hash
Hi prateekbh

First of all, thank you for this great plugin! A nice way to ship less code.

However, I just encountered a bug: The filename `[hash]` and `[chunkhash]` don't match those used otherwise by Webpack - this makes cache busting impossible when not using the HTML plugin.

Best regards,
Fabian von Ellerts

### PR DESCRIPTION
**Pull request by prateekbh**
fixes #15

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
this is 2 things in 1 pr, or is the aliasing required for the hash thing?

**Comment by prateekbh** [comment]
woops my bad

**Comment by prateekbh** [comment]
yeah i added two things in one branch

**Comment by prateekbh** [comment]
opening other one with one feature at a time

**Comment by prateekbh** [comment]
also for aliasing modules, @developit has a better PR

**Pull request closed without merging**
